// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.https://ymxgpiuznxgazbavlpmk.supabase.co;
const SUPABASE_PUBLISHABLE_KEY = import.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlteGdwaXV6bnhnYXpiYXZscG1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM0MTc4NDQsImV4cCI6MjA4ODk5Mzg0NH0.d4sRPctdXU8WIpaRvm-LLh2pOC5U3xtWuKeMrjmg-_g;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});